dh:
  keycloak:
    realm: avaliacao-back
    serverUrl: http://localhost:8082/
    clientId: users-service
    clientSecret: jTKhqmdCbuqyjpAlsmOvGUac57i4W416
spring:
  application:
    name: users-service

  security:
    oauth2:
      client:
        registration:
          keycloak-registration:
            provider: keycloak-provider
            client-id: users-service
            authorization-grant-type: client_credentials
            client-secret: jTKhqmdCbuqyjpAlsmOvGUac57i4W416
        provider:
          keycloak-provider:
            token-uri: http://localhost:8082/realms/avaliacao-back/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/avaliacao-back

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG

server:
  port: 8087
